import { NextRequest, NextResponse } from 'next/server'
import { supabase } from '@/lib/supabase'

export const dynamic = 'force-dynamic'

/**
 * API para criar um novo profissional
 */
export async function POST(request: NextRequest) {
  try {
    const { nome, email, senha, telefone } = await request.json()

    // Validações
    if (!nome || !email || !senha) {
      return NextResponse.json(
        {
          success: false,
          message: 'Nome, email e senha são obrigatórios',
        },
        { status: 400 }
      )
    }

    if (senha.length < 6) {
      return NextResponse.json(
        {
          success: false,
          message: 'A senha deve ter no mínimo 6 caracteres',
        },
        { status: 400 }
      )
    }

    // Verifica se o email já existe
    const { data: profissionalExistente, error: errorBusca } = await supabase
      .from('profissional_anamnese')
      .select('id, email')
      .eq('email', email)
      .maybeSingle()

    if (errorBusca) {
      console.error('Erro ao verificar email:', errorBusca)
      return NextResponse.json(
        {
          success: false,
          message: 'Erro ao verificar email. Tente novamente.',
        },
        { status: 500 }
      )
    }

    if (profissionalExistente) {
      return NextResponse.json(
        {
          success: false,
          message: 'Este email já está cadastrado',
        },
        { status: 400 }
      )
    }

    // Prepara os dados para inserção na tabela profissional_anamnese
    const dadosProfissional = {
      nome,
      email,
      senha,
      telefone: telefone || null,
      // created_at será preenchido automaticamente pelo banco (default now())
      // id será gerado automaticamente pelo banco (generated by default as identity)
    }

    console.log('[DEBUG] Inserindo profissional na tabela profissional_anamnese:', {
      nome,
      email,
      telefone: telefone || null,
      senha: '***' // Não logar a senha por segurança
    })

    // Insere o novo profissional na tabela profissional_anamnese
    const { data: novoProfissional, error: errorInsert } = await supabase
      .from('profissional_anamnese')
      .insert([dadosProfissional])
      .select('id, nome, email, telefone, created_at')
      .single()

    if (errorInsert) {
      console.error('[DEBUG] Erro ao criar profissional:', errorInsert)
      return NextResponse.json(
        {
          success: false,
          message: 'Erro ao criar conta. Tente novamente.',
          error: process.env.NODE_ENV === 'development' ? errorInsert.message : undefined,
        },
        { status: 500 }
      )
    }

    console.log('[DEBUG] Profissional criado com sucesso:', {
      id: novoProfissional?.id,
      nome: novoProfissional?.nome,
      email: novoProfissional?.email,
    })

    return NextResponse.json(
      {
        success: true,
        message: 'Conta criada com sucesso!',
        profissional: novoProfissional,
      },
      { status: 201 }
    )
  } catch (error) {
    console.error('Erro ao criar profissional:', error)
    return NextResponse.json(
      {
        success: false,
        message: 'Erro ao processar cadastro.',
      },
      { status: 500 }
    )
  }
}
